### ISSUE TITLE
Livewire 3

### ISSUE THREAD

**Issue by jeffchown** [masmerise/livewire-toaster#14]
Hello,

Great work on the library.

Any timeline on Livewire 3 (https://livewire.laravel.com/docs/upgrading) compatibility?

Thanks!

**Comment by mabdullahsari** [comment]
It's still in beta. v3 support will be added once it's out and has a stable release.

**Comment by jeffchown** [comment]
Thanks for the quick response, @mabdullahsari !

Do you have a dev branch for using your package with the Livewire beta that I could pull to prepare for the stable release?

**Comment by mabdullahsari** [comment]
> Thanks for the quick response, @mabdullahsari !
> 
> Do you have a dev branch for using your package with the Livewire beta that I could pull to prepare for the stable release?

I'm afraid I don't, sorry. I'll try preparing a PR somewhere this week or early next week after having had a gander at the breaking changes. I understand it's a bit irritating for you, but a beta release can still introduce breaking changes and I'd rather avoid unnecessary work. I'll ping you here once I have something up and running. Sounds good?

**Comment by jeffchown** [comment]
No worries, @mabdullahsari - not irritated at all.  Just mapping a timeline for a client project (that uses your package) that I would like to upgrade to Livewire 3.

Makes sense (re: avoiding unnecessary work).  Sounds good 👍

**Comment by mabdullahsari** [comment]
A'ight. I'll keep you posted, then. Thanks for using `Toaster`!  👍

**Comment by gazzoy** [comment]
I'm looking forward to this update too!👍

**Comment by mabdullahsari** [comment]
Okay, so a quick update for y'all. 

It looks like the release date of Livewire 3 is still uncertain and is likely to [last at least a month](https://twitter.com/nicolaibaaring/status/1685235435436470272). However recently, I've also seen that [Filament will be launching v3](https://twitter.com/danjharrin/status/1686062812181774354). But I have a hunch they'll just be "yolo" releasing while Livewire 3 is still in beta. When I look at [Livewire 3's repository activity](https://github.com/livewire/livewire/commits/main), it's pretty obvious they're still working on a bunch of fixes and restoring old behavior that used to work but does not in the new version.

My time is pretty limited, so I still cannot afford the fact that breaking changes can happen at any time and old features that might be missing. That's why now I have to make the decision to not work on a v3 upgrade until Caleb properly announces a release date for Livewire 3.

Thanks for your understandings.

**Comment by gazzoy** [comment]
> My time is pretty limited, so I still cannot afford the fact that breaking changes can happen at any time and old features that might be missing. That's why now I have to make the decision to not work on a v3 upgrade until Caleb properly announces a release date for Livewire 3.

Sure, that totally makes sense. No need to be hasty :D

**Comment by mabdullahsari** [comment]
I went ahead and carried out the necessary changes in order to support Livewire 3: https://github.com/masmerise/livewire-toaster/pull/16. You can try it out by replacing the current version number with `dev-livewire-3` as the version name in your `composer.json` files.

Please do provide feedback in the meantime. Thanks!
