### ISSUE TITLE
Suddenly reciving the following console errors

### ISSUE THREAD

**Issue by fredbradley** [masmerise/livewire-toaster#57]
![image](https://github.com/user-attachments/assets/e53ace72-36b8-4a5c-a826-da8c412324ce)

It seems that these are there by default... on first page load.

**Comment by mabdullahsari** [comment]
The initial toasts value can never be `null` due to [this line](https://github.com/masmerise/livewire-toaster/blob/271562d2d3d61bd2bcd0c3fa4a25ac2c1900b9f4/src/ToasterHub.php#L27).

Can you provide a bit more information? When did this happen? Have you tried playing around with something like flashing the session variable yourself etc? Thanks!

**Comment by mabdullahsari** [comment]
Hey, do you have something to share that would make debugging possible?

**Comment by mabdullahsari** [comment]
Raise another issue if you still encounter it at any point in the future!
